# This is a dummy workflow file to test actions using actionlint.
# This workflow is never run.
name: test action (actionlint)
on: workflow_call
jobs:
  actionlint-action:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: ./
        with:
          app_id: dummy
          app_private_key: dummy
          server_repository: demo-server

      - uses: ./parse-label
        id: pr
      - uses: ./validate
        id: validate
        with:
          github_token: xxx
          pull_request_number: ${{ steps.pr.outputs.pull_request_number }}
          repository_owner: ${{ steps.pr.outputs.repository_owner }}
          repository_name: ${{ steps.pr.outputs.repository_name }}
      - uses: ./approve
        if: steps.validate.outputs.approved == 'true'
        with:
          github_token: xxx
          pull_request_number: ${{ steps.pr.outputs.pull_request_number }}
          repository_owner: ${{ steps.pr.outputs.repository_owner }}
          repository_name: ${{ steps.pr.outputs.repository_name }}
          sha: ${{ steps.validate.outputs.approved_sha }}
